// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using PieShopAPI.Models;

namespace PieShopAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    internal class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PieShopAPI.Models.Pie", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("ImageThumbnailUrl");

                b.Property<string>("ImageUrl");

                b.Property<bool>("IsPieOfTheWeek");

                b.Property<string>("LongDescription");

                b.Property<string>("Name");

                b.Property<decimal>("Price");

                b.Property<string>("ShortDescription");

                b.HasKey("Id");

                b.ToTable("Pies");
            });
#pragma warning restore 612, 618
        }
    }
}